### ISSUE TITLE
Rubic Score

### ISSUE THREAD

**Issue by Kavit900** [thepicklekid77/pjs-capstone-lodash#4]
**Criteria 1:** Functionality
_Score Level:_ 4 Exceeds Expectations

**Criteria 2:** Code Style - Formatting
_Score Level:_ 3 Meets Expectations
_Comments:-_ I feel it could be more better, checkout issue number `2` and `3` for this and we can improve on top of it.

**Criteria 3:** Code Style - Javascript
_Score Level:_ 3 Meets Expectations
_Comments:-_ For reference take a look at issue number `1`, basically few methods require code factoring and reuse, also give very high importance to comments as it helps other developers to understand what's happening inside of the method.

**Overall Score:** 10/12

Great job! Next Steps would be take a look at the minor comments and approaches mentioned above but overall from my side, I was really impressed with the code quality and functionality.

**Comment by loftingWonder** [comment]
Very cool, thank you.  Would you recommend adding an ES Lint Rules on top of my IDE to improve my formatting?  

Also, can you help me understand what you meant here?  " basically few methods require code factoring"?

**Comment by Kavit900** [comment]
Hi @thepicklekid77  yes that would be good to add ES Lint Rules on top of your IDE. 

For the second point, basically think how you can use `clamp` method with `inRange` method.
